### ISSUE TITLE
Node.js/server support

### ISSUE THREAD

**Issue by OliverJAsh** [argo-rest/theseus#1]
1. Adapter support: Whilst none of the bundled HTTP adapters work in Node.js, I am personally interested in using (and am using, in the case of Argonaut) Theseus on the server. (I've written an adapter for [request](https://github.com/mikeal/request): https://github.com/OliverJAsh/sbscribe/blob/ccf5e106eff7b969984275b98c2d53611137caae/sbscribe-common/lib/request-http-adapter.js).
2. This package can't be consumed with Node.js because it is using ES6. You can compile the module on export like so: https://github.com/OliverJAsh/sbscribe/commit/8b2a002. P.S. Domenic has spoken of abstracting this "compile on export" functionality here: https://github.com/dglazkov/html-as-custom-elements/blob/021bba91cae1b65d1dd486730875a651449803d6/scripts/traceur-runner.js#L5

**Comment by theefer** [comment]
@OliverJAsh Do you want to test this again with `jspm run`? Should work now, as long as you have an any-http adapter for Node (let's make it official if it works).

**Comment by theefer** [comment]
Closing as there is no reason why it shouldn't work.
